const DB_NAME = 'mold-parameter-library';
const STORE = 'molds';
let db, molds = [], currentId = null, dirty = false;

const $ = (s, root = document) => root.querySelector(s);
const $$ = (s, root = document) => [...root.querySelectorAll(s)];
const uid = () => crypto.randomUUID ? crypto.randomUUID() : `${Date.now()}-${Math.random()}`;
const esc = (s = '') => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

function openDb(){return new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,1);req.onupgradeneeded=()=>req.result.createObjectStore(STORE,{keyPath:'id'});req.onsuccess=()=>{db=req.result;resolve(db)};req.onerror=()=>reject(req.error)})}
function dbAll(){return new Promise((resolve,reject)=>{const r=db.transaction(STORE).objectStore(STORE).getAll();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
function dbGet(id){return new Promise((resolve,reject)=>{const r=db.transaction(STORE).objectStore(STORE).get(id);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
function dbPut(v){return new Promise((resolve,reject)=>{const r=db.transaction(STORE,'readwrite').objectStore(STORE).put(v);r.onsuccess=()=>resolve();r.onerror=()=>reject(r.error)})}
function dbDelete(id){return new Promise((resolve,reject)=>{const r=db.transaction(STORE,'readwrite').objectStore(STORE).delete(id);r.onsuccess=()=>resolve();r.onerror=()=>reject(r.error)})}

function blankRows(count, rowNames){return rowNames.map(name=>({name,values:Array(count).fill('')}))}
function emptyMold(){return {id:uid(),code:'',name:'未命名模具',machine:'',product:'',material:'',cavities:'',owner:'',status:'待验证',quickTip:'',transferMode:'时间',transferValue:'',openStroke:'',platenPosition:'',thrustPosition:'',ejectorMode:'定次',ejectorCount:'',ejectorPosition:'',tables:{injection:blankRows(6,['位置 (mm)','压力 (bar)','速度 (%)']),holding:blankRows(6,['压力 (bar)','速度 (%)','时间 (s)']),open:blankRows(5,['位置 (mm)','压力 (bar)','速度 (%)']),close:blankRows(5,['位置 (mm)','压力 (bar)','速度 (%)']),ejectForward:blankRows(2,['位置 (mm)','压力 (bar)','速度 (%)','延迟 (s)']),ejectBack:blankRows(2,['位置 (mm)','压力 (bar)','速度 (%)','延迟 (s)'])},hoses:[],notes:[],createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}}
function demoMold(){const m=emptyMold();Object.assign(m,{code:'1255D0005',name:'示例模具',status:'待验证',quickTip:'参数依据现场照片录入，请首次上机时由师傅复核。',openStroke:'260.0',platenPosition:'269.8',thrustPosition:'233.1',ejectorMode:'定次',ejectorCount:'2',ejectorPosition:'0.2',transferMode:'时间',transferValue:'7.00'});m.tables.injection=[{name:'位置 (mm)',values:['0.0','0.0','0.0','0.0','0.0','20.0']},{name:'压力 (bar)',values:['0','0','0','0','60','62']},{name:'速度 (%)',values:['0','0','0','0','18','22']}];m.tables.holding=blankRows(6,['压力 (bar)','速度 (%)','时间 (s)']);m.tables.open=[{name:'位置 (mm)',values:['200.0','200.0','35.0','1.80','']},{name:'压力 (bar)',values:['30','30','25','8','120']},{name:'速度 (%)',values:['30','30','25','15','25']}];m.tables.close=[{name:'位置 (mm)',values:['260.0','200.0','100.0','40.0','5.0']},{name:'压力 (bar)',values:['55','55','80','80','120']},{name:'速度 (%)',values:['30','30','30','15','20']}];m.tables.ejectForward=[{name:'位置 (mm)',values:['42.0','43.0']},{name:'压力 (bar)',values:['85','85']},{name:'速度 (%)',values:['35','35']},{name:'延迟 (s)',values:['0.00','']}];m.tables.ejectBack=[{name:'位置 (mm)',values:['1.0','40.0']},{name:'压力 (bar)',values:['65','65']},{name:'速度 (%)',values:['50','50']},{name:'延迟 (s)',values:['','0.00']}];return m}

function buildTable(id,key,labels){const table=$(id);table.innerHTML=`<thead><tr><th>参数</th>${labels.map(s=>`<th>${s}</th>`).join('')}</tr></thead><tbody></tbody>`;const body=$('tbody',table);const m=current();(m?.tables[key]||[]).forEach((row,ri)=>{const tr=document.createElement('tr');tr.innerHTML=`<td>${esc(row.name)}</td>${row.values.map((v,ci)=>`<td><input type="number" step="any" data-table="${key}" data-row="${ri}" data-col="${ci}" value="${esc(v)}"></td>`).join('')}`;body.appendChild(tr)})}
function current(){return molds.find(m=>m.id===currentId)}
function renderTables(){buildTable('#injectionTable','injection',['六段','五段','四段','三段','二段','一段']);buildTable('#holdingTable','holding',['六段','五段','四段','三段','二段','一段']);buildTable('#openTable','open',['一段','二段','三段','低压','高压']);buildTable('#closeTable','close',['五段','四段','三段','二段','一段']);buildTable('#ejectForwardTable','ejectForward',['一段','二段']);buildTable('#ejectBackTable','ejectBack',['二段','一段'])}
function renderList(){const q=$('#searchInput').value.trim().toLowerCase();const filtered=molds.filter(m=>`${m.code} ${m.name} ${m.product} ${m.machine}`.toLowerCase().includes(q)).sort((a,b)=>(b.updatedAt||'').localeCompare(a.updatedAt||''));$('#moldCount').textContent=filtered.length;$('#moldList').innerHTML=filtered.map(m=>`<div class="mold-item ${m.id===currentId?'active':''}" data-id="${m.id}"><strong>${esc(m.code||'未填写编号')}</strong><span>${esc(m.name||'未命名模具')}</span><span class="status">${esc(m.status||'未设置')}</span></div>`).join('');$('#emptyState').classList.toggle('hidden',molds.length>0);$('#editor').classList.toggle('hidden',molds.length===0)}
function fillForm(m){$$('#moldForm [name]').forEach(el=>{if(Object.prototype.hasOwnProperty.call(m,el.name))el.value=m[el.name]??''});$('#pageTitle').textContent=`${m.code||'未填写编号'} · ${m.name||'未命名模具'}`;renderTables();renderHoses();renderNotes();setDirty(false)}
function readSimpleFields(){const m=current();if(!m)return;$$('#moldForm [name]').forEach(el=>m[el.name]=el.value);m.updatedAt=new Date().toISOString()}
function setDirty(v=true){dirty=v;$('#saveStatus').textContent=v?'有未保存更改':'已保存';$('#saveStatus').classList.toggle('unsaved',v)}
function mark(){readSimpleFields();setDirty(true);const m=current();if(m){$('#pageTitle').textContent=`${m.code||'未填写编号'} · ${m.name||'未命名模具'}`}}
async function allowDiscard(){if(!dirty)return true;if(!confirm('当前修改尚未保存，确定放弃这些修改吗？'))return false;const saved=await dbGet(currentId);const idx=molds.findIndex(x=>x.id===currentId);if(saved&&idx>=0)molds[idx]=saved;setDirty(false);return true}
async function selectMold(id){if(id===currentId)return;if(!await allowDiscard())return;currentId=id;renderList();fillForm(current())}
async function save(){const m=current();if(!m)return;readSimpleFields();if(!m.code.trim()||!m.name.trim()){toast('请先填写模具编号和名称');showTab('basic');return}if(molds.some(x=>x.id!==m.id&&x.code.trim().toLowerCase()===m.code.trim().toLowerCase())){toast('模具编号已存在，请使用唯一编号');showTab('basic');return}await dbPut(m);setDirty(false);renderList();toast('已保存')}
async function createMold(copy=false){if(!await allowDiscard())return;const m=copy?structuredClone(current()):emptyMold();m.id=uid();m.createdAt=new Date().toISOString();m.updatedAt=m.createdAt;if(copy){m.code=`${m.code}-副本`;m.name=`${m.name}（副本）`;m.notes=(m.notes||[]).map(n=>({...n,id:uid()}))}molds.push(m);currentId=m.id;await dbPut(m);renderList();fillForm(m);showTab('basic');toast(copy?'已复制，请修改编号':'已新建模具')}
async function removeCurrent(){const m=current();if(!m||!confirm(`确定删除“${m.code} ${m.name}”吗？此操作无法撤销。`))return;await dbDelete(m.id);molds=molds.filter(x=>x.id!==m.id);currentId=molds[0]?.id||null;renderList();if(currentId)fillForm(current());toast('已删除')}
function showTab(tab){$$('.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===tab));$$('.tab-panel').forEach(x=>x.classList.toggle('active',x.dataset.panel===tab))}

function renderHoses(){const m=current(),list=$('#hoseList');list.innerHTML=(m.hoses||[]).map((h,i)=>`<div class="hose-card" data-hose="${i}"><div class="hose-head"><strong>油管 ${i+1}</strong><button type="button" class="button danger small" data-remove-hose="${i}">删除</button></div><div class="hose-grid"><label><span>接口 / 编号</span><input data-hose-field="port" value="${esc(h.port)}" placeholder="例如：A1"></label><label><span>用途</span><input data-hose-field="purpose" value="${esc(h.purpose)}" placeholder="例如：左侧抽芯"></label><label><span>规格</span><input data-hose-field="spec" value="${esc(h.spec)}" placeholder="例如：3/8 快接"></label><label><span>数量</span><input data-hose-field="quantity" type="number" min="0" value="${esc(h.quantity)}"></label><label><span>连接位置 / 方向</span><input data-hose-field="connection" value="${esc(h.connection)}" placeholder="例如：操作侧上方"></label><label><span>备注</span><input data-hose-field="remark" value="${esc(h.remark)}"></label></div></div>`).join('');$('#hoseEmpty').classList.toggle('hidden',(m.hoses||[]).length>0)}
function addHose(){current().hoses.push({port:'',purpose:'',spec:'',quantity:'1',connection:'',remark:''});renderHoses();setDirty(true)}
function renderNotes(){const m=current(),list=$('#noteList');list.innerHTML=(m.notes||[]).map((n,i)=>`<div class="note-card" data-note="${i}"><div class="note-head"><strong>备注 ${i+1}</strong><button type="button" class="button danger small" data-remove-note="${i}">删除</button></div><textarea data-note-text="${i}" placeholder="输入调机要点、异常处理或注意事项…">${esc(n.text)}</textarea><div class="note-images">${(n.images||[]).map((img,j)=>`<div class="note-image"><img src="${img.data}" alt="备注图片"><button type="button" class="image-remove" data-remove-image="${i}:${j}">×</button></div>`).join('')}</div><label class="image-upload">＋ 添加图片<input type="file" accept="image/*" multiple data-note-image="${i}"></label></div>`).join('');$('#noteEmpty').classList.toggle('hidden',(m.notes||[]).length>0)}
function addNote(){current().notes.push({id:uid(),text:'',images:[]});renderNotes();setDirty(true)}
function fileData(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)})}
async function addImages(noteIndex,files){for(const file of [...files]){if(file.size>5*1024*1024){toast(`${file.name} 超过 5MB，已跳过`);continue}current().notes[noteIndex].images.push({name:file.name,type:file.type,data:await fileData(file)})}renderNotes();setDirty(true)}

function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2200)}
async function exportData(){if(dirty)await save();const blob=new Blob([JSON.stringify({version:1,exportedAt:new Date().toISOString(),molds},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`模具参数备份_${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)}
async function importData(file){try{const data=JSON.parse(await file.text());if(!Array.isArray(data.molds))throw new Error();if(!confirm(`备份中有 ${data.molds.length} 条模具记录。导入将按编号覆盖同名记录，是否继续？`))return;for(const incoming of data.molds){const old=molds.find(x=>x.code&&x.code===incoming.code);if(old)incoming.id=old.id;else incoming.id=incoming.id||uid();await dbPut(incoming);const idx=molds.findIndex(x=>x.id===incoming.id);if(idx>=0)molds[idx]=incoming;else molds.push(incoming)}currentId=molds[0]?.id||null;renderList();if(currentId)fillForm(current());toast('导入完成')}catch{toast('备份文件格式不正确')}}

document.addEventListener('click',e=>{const item=e.target.closest('.mold-item');if(item)selectMold(item.dataset.id);if(e.target.closest('[data-action="new"]'))createMold()});
$('#tabs').addEventListener('click',e=>{const tab=e.target.closest('.tab');if(tab)showTab(tab.dataset.tab)});
$('#moldForm').addEventListener('input',e=>{const t=e.target;if(t.dataset.table){current().tables[t.dataset.table][+t.dataset.row].values[+t.dataset.col]=t.value;setDirty(true)}else if(t.dataset.hoseField){current().hoses[+t.closest('[data-hose]').dataset.hose][t.dataset.hoseField]=t.value;setDirty(true)}else if(t.dataset.noteText!==undefined){current().notes[+t.dataset.noteText].text=t.value;setDirty(true)}else if(t.name)mark()});
$('#moldForm').addEventListener('change',e=>{if(e.target.dataset.noteImage!==undefined)addImages(+e.target.dataset.noteImage,e.target.files)});
$('#moldForm').addEventListener('click',e=>{if(e.target.dataset.removeHose!==undefined){current().hoses.splice(+e.target.dataset.removeHose,1);renderHoses();setDirty(true)}if(e.target.dataset.removeNote!==undefined){current().notes.splice(+e.target.dataset.removeNote,1);renderNotes();setDirty(true)}if(e.target.dataset.removeImage){const[i,j]=e.target.dataset.removeImage.split(':').map(Number);current().notes[i].images.splice(j,1);renderNotes();setDirty(true)}});
$('#searchInput').addEventListener('input',renderList);$('#newMoldBtn').onclick=()=>createMold();$('#duplicateBtn').onclick=()=>createMold(true);$('#deleteBtn').onclick=removeCurrent;$('#saveBtn').onclick=save;$('#addHoseBtn').onclick=addHose;$('#addNoteBtn').onclick=addNote;$('#exportBtn').onclick=exportData;$('#importInput').onchange=e=>{if(e.target.files[0])importData(e.target.files[0]);e.target.value=''};
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});

(async function init(){await openDb();molds=await dbAll();if(!molds.length){const demo=demoMold();molds=[demo];await dbPut(demo)}currentId=molds[0]?.id||null;renderList();if(currentId)fillForm(current())})().catch(()=>alert('浏览器无法打开本地数据库，请使用最新版 Chrome 或 Edge。'));
